version: '3.1'

services:

  mongo:
    image: mongo
    restart: always

    volumes:
      - ./restaurants.json:/tmp/restaurants.json
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
