version: '3.0'

services:
  todo-app:
    image: postgres:16.0
    container_name: postgres
    env_file:
      - ./postgres/postgres.env
    volumes:
      - ./postgres/init/:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  #play-scala-backend:
  #  build: 
  #    dockerfile: ./PlayScala.Dockerfile
  #    context: .
  #
  #  ports:
  #    - "8080:9000"



    